### ISSUE TITLE
showAdvanceControl does not have an effect on sequences

### ISSUE THREAD

**Issue by anbjoernskov** [cadin/panels#15]
After the update with the new nonlinear story, setting `showAdvanceControl = false` for a sequence, does not cause the last panel to not have an advance control. But setting the non-linear `showAdvanceControls = false`, does work, and make the advance control disappear.

From Panels.lua

```
if sequence.showAdvanceControls == nil then
   sequence.showAdvanceControls = sequence.showAdvanceControl or true
end
```

Could this be enough to cover all cases?
```
	if sequence.showAdvanceControls == nil and sequence.showAdvanceControl == nil then
		sequence.showAdvanceControls = true
	end

	if sequence.showAdvanceControl ~= nil then
		sequence.showAdvanceControls = sequence.showAdvanceControl
	end
```

**Comment by cadin** [comment]
This should be fixed if you pull down the latest version of Panels.
That means either pulling the git submodule, or just re-downloading the Panels code are replacing everything in `source/libraries/Panels`.

Thanks!
