### ISSUE TITLE
Large frames has a low framerate on HW

### ISSUE THREAD

**Issue by anbjoernskov** [cadin/panels#17]
Hello again.

I have some issues with larger frames, e.g. a frame that is around 420x1500 pixels (also the other way). When I set the panel that size the frame rate on the device drops to around 15 FPS - which is not super nice.

I tried having the same layers, but only having the frame size the normal 420x200, and then e.g. scrolling the picture by modifying the layer.x property in the update function, and by doing this I get 30 FPS.

So it doesn't seem to be the size of the images (layers) or the amount of them, but the problem seems to be that the playdate thinks it needs to draw everything, eventhough it is not displayed.

Do you think there could be an optimization for this? Or what would a good strategy be for avoiding this?

Thanks again for all your help - the game is finished soon, and I promise I will sent you a copy :)

**Comment by anbjoernskov** [comment]
Don't know if you have tried with the drawOffset?
https://sdk.play.date/2.1.1/Inside%20Playdate.html#f-graphics.setDrawOffset

**Comment by cadin** [comment]
Oof, yeah, each panel gets rendered to an image the size of the frame before getting drawn to screen, so extra large frames like that create large images.

I'll try to take a look at rethinking that, but it will be a pretty big change, and I'm not that confident in my optimization skills.

One thing that can help is cutting out the extra space in images. Panels won't draw an image layer if it's not on screen, so if you have images that are mostly transparent with a small image area, you can get better performance by cutting out the transparency and having a smaller image. That way they'll be on screen for less time and won't be getting drawn when they're not visible.

**Comment by anbjoernskov** [comment]
I tried experimenting a bit yesterday, and it seems to greatly improve the performance if the canvas is just the screensize, and then using the setDrawOffset before the `drawPanels` method, and using the offset. That at least work for a single panel - then the big thing is how to make the transition from one panel to another.

I think ideally you would create a single long image combined of all the images - or do it slowly, and then just have a single canvas the size of the screen. But then the borders and other things needs a bit more work before the work.

For most of my large frame, there are a single panel in a sequence, so I can manage with a hack in the Panels framework.

I tried looking at your comic "To Dust" just to see if you had the same drop in FPS, and there is a few places where you have two panels next to each other, where one of them is a larger one, then it drops to 20 FPS, but it is not as bad as in my case, and it is only when both panels are visible at the same time.

**Comment by cadin** [comment]
I started going down that route at one point, but it didn't make sense to me that `large image > small image > screen` would be faster than `large image > screen`. I was assuming the hardware does some optimization to not try to draw image pixels that are off screen. I guess I was wrong about that? Or maybe something else related to the large canvas is causing the slowdown. 

I have some time later this week when I can take a look. Thanks for your help.

**Comment by anbjoernskov** [comment]
I have tried to hack something here: https://github.com/anbjoernskov/panels/commit/bc443ed4aaabd747f688a8e6a437f98eb2ebdec9

There quite a lot of limitations with my hack - and that's why I also need to limit the offsets, otherwise parallaxing layers would fly out of the frame.

But the framerate is 30 FPS when using this, and it was 14 FPS before, so there is definitely something there.

Maybe it is because is actually trying to draw the entire canvas, even though it cannot fit the screen?

With my hack - I get the same parallaxing, etc, as before, as I set the drawOffset before the drawLayers method.

**Comment by anbjoernskov** [comment]
I found a solution for making sure that the things stay within the frame. Using the https://sdk.play.date/2.1.1/Inside%20Playdate.html#f-graphics.setClipRect, it works by doing:

```
		if self.hack then
			gfx.setDrawOffset(offset.x, offset.y)
			gfx.setClipRect(self.frame.x, self.frame.y, self.frame.width, self.frame.height)
		end
```

But it doesn't work for multiple panels - but I think it should be possible to do, but I think there will be quite a lot to change, as instead of having two separate images that you scroll and have to draw different places, I think everything might need to be in the same canvas, and then just be separate rects that is looked at.

**Comment by cadin** [comment]
I made some changes on the [`optimization`](https://github.com/cadin/panels/tree/optimization) branch.

The Panel canvas is now limited to only the screen size (instead of the full panel size).
In my test this gets me an extra 5fps, but still lags below 30 when two panels are on screen.

Can you take a look at that branch and see if it will work for you?

I think to optimize further I'd need to do a similar change for every layer in the panel, which I'm not really eager to do.

**Comment by anbjoernskov** [comment]
It works very well. The only thing I need is that the updateFunction is called before the setDrawOffset, so that it is:
```
		if self.updateFunction then 
			self:updateFunction(offset)
		end

		gfx.setDrawOffset(offset.x + frame.x, offset.y + frame.y)
		gfx.setClipRect(0, 0, frame.width, frame.height)
		gfx.clear(self.backgroundColor)
```

This is because I need to update the offset with the crank in the update function. :)


Another thing I found is that the text layers were a bit heavy. There was a place where I had four text boxes, and it was really slow.
I think the code for the drawTextLayer maybe should have been like this? Otherwise it redraws a static text box everytime:

```
		if(layer.cachedTextImg == nil) then
			layer.cachedTextImg = gfx.image.new(ScreenWidth, ScreenHeight)
			layer.needsRedraw = true
		else
			layer.needsRedraw = false
		end
```

**Comment by cadin** [comment]
Ok, this is all in `main` now.

Good catch on the text caching. I was resetting it for animated layers, but not static.

Thanks again for your help!

**Comment by anbjoernskov** [comment]
Hmm -  I was a bit puzzled because I got an improvement in FPS with your new branch, but then I noticed that it wasn't as good as with my hack. But it really looked like you did almost the same as me. So I have tried looking a line per line of your changes, and applied them until my FPS dropped. And it is really weird and I don't know exactly what is happening. But it was the background color of the new image that was different! So this change
![image](https://github.com/cadin/panels/assets/77576836/4f407f99-19de-4001-a80b-cb85b47ac401)

I am super puzzled by this, but my guess is that it could have something to do with this comment in the documentation here: https://sdk.play.date/2.1.1/Inside%20Playdate.html#m-graphics.image.clear

If the image is cleared to 'Clear' a mask is added. That might make it more expensive to compute?

Did you have any particular reason to change, so that the background is clear?

**Comment by cadin** [comment]
Yeah, the transparency is needed so adjacent panels don’t overdraw each other. But maybe I can get rid of it and use cliprect higher up the render stack. I thought I tried that and didn’t see much difference, but I can take another look. Good to know that’s where the slowdown is. On Nov 26, 2023, at 12:19 PM, anbjoernskov ***@***.***> wrote:﻿
Ahh - I didn't look at a sequence with more than one panel before - I can see now why you did it... Hmm - but weird that it is so expensive...

**Comment by anbjoernskov** [comment]
Maybe it would be even better to just pushContext at the beginning of the drawComic, and then first popContext at the end, and then also put the draw at the end, as there will only be one canvas to draw?

**Comment by cadin** [comment]
This gets me another 5 or 6 fps. It still dips below 30 when multiple panels are on screen:
[develop branch](https://github.com/cadin/panels/tree/develop)

I pretty much did what you said: one main canvas for Panels. Push the context and let each panel draw directly to that image. I got rid of the transparent clear, and only clear with the bg color if a panel explicitly sets one.

**Comment by anbjoernskov** [comment]
I have tried your develop branch, and it just works perfectly!

I get 30 FPS on almost everything. And then I have optimized the layers, so that they are smaller, and combined some that didn't needed to be separate.

So I think the performance from the framework has improved a lot, a now it is a question of how many layers are active. Maybe that is also what you see when multiple panels are on the screen - there are simply more layers that needs to be drawn.

Thank you very much for your swift implementation and eager to improve!

**Comment by cadin** [comment]
Awesome, I've pushed it to `main`.

Thanks again for your help. I know I'm doing a lot of things inefficiently, but it's hard to know which parts will be worth the effort to optimize. It was really helpful that you were able to track down those problems.
