### ISSUE TITLE
Parallax documentation is backwards

### ISSUE THREAD

**Issue by ebeneliason** [cadin/panels#22]
From the docs:
> The amount of parallax movement to apply to this layer (between 0 and 1). A layer with a higher value will move more in relation to the frame border. In general, layers closer to the viewer should have a higher parallax value than layers in the distance.

Based on my experimentation, it appears that a layer with a `parallax` value of `0` will actually move the most, as though very near to the camera, whereas those with a value of `1` appear furthest away. This was counterintuitive until I realized that the parallax is being applied as a _negative_ shift relative to the scrolling of the panel. A higher value yields a higher negative shift, and thus the least net movement.

**Comment by cadin** [comment]
You're right, the last sentence should say "In general, layers closer to the viewer should have a _lower_ parallax value than layers in the distance."

The first part is accurate in that higher numbers move more _in relation to the panel frame_. But that means they move _less_ in relation to the Playdate screen. Confusing. 

If you can think of a better blurb to describe that I'm open to suggestions.

**Comment by ebeneliason** [comment]
Ah, that makes sense. It's interesting to see that first part from the other perspective. Changing the last sentence seems the only essential fix, but to suggest a potential clarification for the other:

> A layer with a higher value will move more in relation to the frame border, and thus less with respect to the playdate screen.
