### ISSUE TITLE
Animating opacity to a lower level removes the image.

### ISSUE THREAD

**Issue by anbjoernskov** [cadin/panels#8]
If animating a layer with an opacity to a lower level, it removes the image instantly. 
If writing code like this.

``` 
{image = "s01/D/evil_toy.png", opacity = 1, animate = {opacity = 0, delay = 450, duration = 100, trigger = Panels.Input.A}},
```
the image will just dissapear.

I found the root cause to be in the Panels module, where the following code is (https://github.com/cadin/panels/blob/d412f0056b8b1c3d6780f8e53e6b4be7fde87354/modules/Panel.lua#L393C7-L393C7):
```
if anim.opacity then
   local o = (anim.opacity - layer.opacity) * layerPct
   layer.alpha = o
   if o <= 0 then
      layer.visible = false
   else
      layer.visible = true
   end
end
```

The `o` is negative when fading to a lower opacity.

**Comment by anbjoernskov** [comment]
I guess the only thing actually needed for this to work would be:

```
if anim.opacity then
   local o = (anim.opacity - layer.opacity) * layerPct + layer.opacity
   layer.alpha = o
   if o <= 0 then
      layer.visible = false
   else
      layer.visible = true
   end
end
```

**Comment by cadin** [comment]
Fixed (https://github.com/cadin/panels/commit/9a38a5e913c64b3b20072ea1bf19f81c322a1ad5).
You can pull the latest to get the fix.

Thanks for your help.

**Comment by anbjoernskov** [comment]
Thank you for a nice framework! :)
