### ISSUE TITLE
Add `transitionOffset` property to Layer

### ISSUE THREAD

**Issue by rubybrowncoat** [cadin/panels#9]
While reading documentation I wrongly assumed `transitionOffset` would be set on a layer with `images`, before eventually realizing my mistake and figuring out that it is applied at the panel level. 

I was wondering if there were any plans to add something like `transitionOffset` to a layer. For example I have a "texts" layer with 3 or 4 images and I would to delay their cadence in relation to another layer of multiple backgrounds that I would instead like to bring forward as far as transition timing goes.

Maybe I'm just approaching it in the wrong way and there is a different way to achieve the same result.

**Comment by cadin** [comment]
That's a good suggestion.

You might be able to work around it by adding duplicate images to the list.  
For example, if you have two images and you want them to transition at 75% instead of 50%, you could list them as:
```
images = { "img1.png", "img1.png", "img1.png", "img2.png" }
```

It's hacky, but might work for you until I can make the change.

**Comment by cadin** [comment]
Added in [v1.4](https://github.com/cadin/panels/releases/tag/v1.4)

[Docs](https://cadin.github.io/panels/docs/comic-data/layers/#transitionoffset)
